# Monitoring stack for Energy Cost Analysis System
version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: energy-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infra/monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - energy-network

  grafana:
    image: grafana/grafana:10.0.0
    container_name: energy-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ops/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - energy-network

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: energy-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./infra/monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    networks:
      - energy-network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.13.2
    container_name: energy-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:dev_password@db:5432/energy_cost?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - energy-network

  redis-exporter:
    image: oliver006/redis_exporter:v1.52.0
    container_name: energy-redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - energy-network

  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: energy-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - energy-network

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  energy-network:
    external: true
